### ISSUE TITLE
Making it possible to easily extend one augmented tensor with new labels/child, even if this is not handle by default.

### ISSUE THREAD

**Issue by thibo73800** [Visual-Behavior/aloception-oss#103]
Making it possible to easily extend one augmented tensor with new labels/child, even if this is not handle by default.
@ragier

**Comment by thibo73800** [comment]
Same question, @anhtu293 @jsalotti , do you think this is still relevant ?

**Comment by jsalotti** [comment]
I think it's already possible to add a child to an existing augmented tensor instance `tensor` by calling `tensor.add_child()`.
