### ISSUE TITLE
CocoBaseDataset : some label names don't work well with Pytorch

### ISSUE THREAD

**Issue by Dee61298** [Visual-Behavior/aloception-oss#233]
Some of the label_names in CocoBaseDataset are "N/A". This works within the dataset, but causes problems with pytorch if I try to export the labels tensor and do some operations on it, namely the following errors : 

RuntimeError: Invalid name: a valid identifier contains only digits, alphabetical characters, and/or underscore and starts with a non-digit. got: 'N/A'.

RuntimeError: Invalid name: a valid identifier contains only digits, alphabetical characters, and/or underscore and starts with a non-digit. got: 'traffic light'.

**Comment by thibo73800** [comment]
`if I try to export the labels tensor`
Not sure what you mean by that, can you give a toy example ?

**Comment by Dee61298** [comment]
Je voulais créer un truc du genre :


labels=aloscene.Labels(x=x,encoding="id",names=frame.boxes2d.labels.labels_names)

Et il faisait les erreurs que j'ai mis dans l'issue.
Mais en fait si j'utilise l'argument "labels_names" au lieu de "names" j'ai
l'impression que c'est bon, donc je crois que c'est juste une erreur de ma
part finalement.

Le mar. 11 oct. 2022 à 15:35, Thibault Neveu ***@***.***> a
écrit :
