### ISSUE TITLE
CocoBaseDataset : can't use test split

### ISSUE THREAD

**Issue by Dee61298** [Visual-Behavior/aloception-oss#234]
I tried to use the test split "test2017" of CocoBaseDataset, which has no annotation file, but the  assert l.81 (https://github.com/Visual-Behavior/aloception-oss/blob/master/alodataset/coco_base_dataset.py#L81) prevents me from doing so.

**Comment by thibo73800** [comment]
It sounds like a quick fix. Can you provide a PR to fix it ?
