### ISSUE TITLE
BoundingBoxes2d _rotate and _spatial_shift implementation doesn't support the case where the box is no longer visible 

### ISSUE THREAD

**Issue by Dee61298** [Visual-Behavior/aloception-oss#239]
**Minimal reproducible example** : [here](https://gitlab.com/aigen-vision/alovb/-/blob/deformable_detr_slam_backend/alovb/archives/deformable_2d_points/test_with_bboxes.py)

**Output** : 
```
Len points before transforms 500
Len boxes before transforms 500
Len points after transforms 439
Len boxes after transforms 500

```

**What happens** : 
I create a random set of aloscene.Points2d, and also a set of aloscene.BoundingBoxes2d whose centers are the random points, with very small height and width. Therefore, the Points2d and the Boxes2d represent the same data.
When I apply alotransforms such as Rotate and SpatialShift to my frame, some of the points are no longer visible. This is taken into account for the Points2d class (the number of points decreases after the transformation) but not in the Boxes2d class where the number of points stays the same no matter if some points/boxes are not visible anymore. 

Also, the lack of implementation of the _rotate function in the BoundingBoxes2d class means that the Points2d are correctly rendered on the rotated frame, but the Boxes2d are rendered as if the frame is not rotated.
![image](https://user-images.githubusercontent.com/104132762/200603225-2ec85e98-e651-448f-9fca-8c7147225833.png)

**Why it matters & why can't I just use the Points2d class ?**

Our DETR implementation uses the Boxes2d class for criterion & hungarian matching. All our implementations that inheritate from DETR also use this class, even Deformable2dPoints that predicts points & not bounding boxes. Therefore, everytime someone adapts DETR to a new project, there is a risk of error.

**Comment by thibo73800** [comment]
Removing points is based only on the center point while removing boxes is based on the visible part of the full boxes (https://github.com/Visual-Behavior/aloception-oss/blob/db7f7707ef5d98330b42ac7e8745154bf41cdd0f/aloscene/bounding_boxes_2d.py#L704). So I think it might me normal that you're Boxes2D don't get removed. 

```
Also, the lack of implementation of the _rotate function in the BoundingBoxes2d class means that the Points2d are correctly rendered on the rotated frame, but the Boxes2d are rendered as if the frame is not rotated.
```
This is a feature, Boxed2D are not supposed to be rotated. Unlike [OrientedB](https://github.com/Visual-Behavior/aloception-oss/blob/master/aloscene/oriented_boxes_2d.py). However we could implement a rotation based only on the center point.

```
Why it matters & why can't I just use the Points2d class ?
```
You should probably consider using Points2d for your application

**Comment by anhtu293** [comment]
@Dee61298 this issue is still opened ?

**Comment by Dee61298** [comment]
I think it can be closed
