### ISSUE TITLE
Unused datasets ?

### ISSUE THREAD

**Issue by Dee61298** [Visual-Behavior/aloception-oss#251]
Some datasets have associated scripts in Alodataset, such as [ChairsSDHom](https://github.com/Visual-Behavior/aloception-oss/blob/master/alodataset/chairssdhom_dataset.py), [Flying Chairs 2](https://github.com/Visual-Behavior/aloception-oss/blob/master/alodataset/flying_chairs2_dataset.py), [MOT](https://github.com/Visual-Behavior/aloception-oss/blob/master/alodataset/mot17.py). However, I don't see any data in /data associated to these datasets. It looks like the only way we use them is by downloading a sample. Given that, does it make sense to keep these scripts at all ? Should we add a message to these datasets to warn the user that they currently can be used only as samples ? 
Ping @thibo73800 I guess

**Comment by thibo73800** [comment]
The dataset can be used if the user download the dataset. We're not supposed to automatically download the dataset. The best we can do is to provide the link to the website to download the dataset
