### ISSUE TITLE
log config when using wandb logger

### ISSUE THREAD

**Issue by jsalotti** [Visual-Behavior/aloception-oss#55]
We should log the training parser arguments in wandb.config object, in order to store information about the training hyperparameters.

This can be done using the `log_hyperparams` method: [WandbLogger.log_hyperparams](https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.WandbLogger.html#pytorch_lightning.loggers.WandbLogger.log_hyperparams)

**Comment by Dee61298** [comment]
closing bc merged
